pod 'AFNetworking', '~> 2.0'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'IOSLinkedInAPI'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'AsyncImageView', '~> 1.5.1'
pod 'iOS-Slide-Menu', '~> 1.4.5'